// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To change this configuration, update the Google Cloud project used by this app.

import { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  "projectId": "coffee-spark-sample-app-bc73f",
  "appId": "1:198751668692:web:3fb688f93402472118ee41",
  "apiKey": "AIzaSyAI1XkNMBqRNPt59plsuP3-MFskCwgibqQ",
  "authDomain": "coffee-spark-sample-app-bc73f.firebaseapp.com",
  "messagingSenderId": "198751668692"
};
