// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To change this configuration, update the Google Cloud project used by this app.

import { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  "apiKey": "API_KEY",
  "authDomain": "coffee-spark-sample-app-bc73f.firebaseapp.com",
  "projectId": "coffee-spark-sample-app-bc73f",
  "storageBucket": "coffee-spark-sample-app-bc73f.appspot.com",
  "messagingSenderId": "1019056637845",
  "appId": "1:1019056637845:web:e4f6b6e45f1b13593b4822"
};
